raw_data = [
    [
        "Dehradun",
        "Nestled in the Doon Valley at the foothills of the Himalayas, Dehradun enjoys a mild climate year-round. "
        "It serves as a gateway to nearby hill stations and is renowned for its educational institutions and colonial architecture. "
        "The city blends natural beauty with cultural heritage, offering a peaceful retreat for travelers.",
        [
            ["Robber's Cave",
             "A natural limestone cave formation with a waterfall and stream running through it, perfect for a refreshing dip.",
             4.5,
             "robbers_cave.jpg"],
            ["Sahastradhara",
             "Known for its sulphur springs and medicinal properties, this waterfall and cave complex is ideal for wellness seekers.",
             4.3,
             "sahastradhara.jpg"],
            ["Tapkeshwar Temple",
             "An ancient cave temple dedicated to Lord Shiva, famous for its natural rock formations and dripping water.",
             4.2,
             "tapkeshwar_temple.jpg"],
            ["Mindrolling Monastery",
             "One of the largest Buddhist learning centers, featuring vibrant murals and a towering stupa.",
             4.6,
             "mindrolling_monastery.jpg"],
            ["Forest Research Institute",
             "Architectural marvel set amidst lush greenery, showcasing botanical gardens and forestry exhibits.",
             4.4,
             "fri.jpg"],
            ["Buddha Temple (Tapovan)",
             "Also known as the Mindroling Monastery's shrine, this temple offers serene gardens and meditation paths.",
             4.5,
             "buddha_temple.jpg"],
            ["Malsi Deer Park",
             "A zoological garden home to deer and other species, popular for family picnics and nature walks.",
             4.0,
             "malsi_deer_park.jpg"],
            ["Lachhiwala",
             "A picnic spot with man-made water pools, dense forests, and a small restaurant overlooking the greenery.",
             4.1,
             "lachhiwala.jpg"],
            ["Rajaji National Park",
             "Sprawling wildlife reserve known for elephants, tigers, and diverse birdlife, with jeep safaris available.",
             4.4,
             None],
            ["Paltan Bazaar",
             "Bustling market area offering local handicrafts, street food, and vibrant cultural experiences.",
             4.2,
             None],
            ["Clock Tower",
             "Historic landmark at the heart of Dehradun city, surrounded by shops and cafés.",
             4.0,
             None],
            ["Canvas Laughs",
             "Popular comedy club hosting stand-up shows, improv nights, and open-mic events.",
             4.3,
             None],
        ]
    ],
    [
        "Agra",
        "Famed worldwide for the Taj Mahal, Agra is steeped in Mughal history and architecture. "
        "Lined by the Yamuna River, the city boasts majestic forts, ornate mausoleums, and bustling bazaars. "
        "Agra’s rich cultural tapestry offers an unforgettable glimpse into India’s imperial past.",
        [
            ["Taj Mahal",
             "Iconic white-marble mausoleum built by Emperor Shah Jahan in memory of his wife, a UNESCO World Heritage Site.",
             4.9,
             "taj_mahal.jpg"],
            ["Agra Fort",
             "Historic red-sandstone fort complex with palaces, halls, and mosques overlooking the Yamuna River.",
             4.7,
             "agra_fort.jpg"],
            ["Fatehpur Sikri",
             "Perfectly preserved ghost city built by Akbar, featuring grand palaces and courtyards.",
             4.6,
             "fatehpur_sikri.jpg"],
            ["Mehtab Bagh",
             "Riverside gardens offering stunning sunset views of the Taj Mahal across the Yamuna.",
             4.3,
             None],
            ["Itmad-ud-Daulah",
             "Often called the 'Baby Taj', this delicate marble tomb predates the Taj Mahal.",
             4.5,
             "itmad_ud_daulah.jpg"],
            ["Jama Masjid",
             "Large mosque near Agra Fort known for its elegant courtyard and sandstone architecture.",
             4.4,
             None],
            ["Akbar's Tomb",
             "Mughal emperor Akbar’s grand mausoleum set in landscaped gardens in Sikandra.",
             4.4,
             "akbar_tomb.jpg"],
            ["Chini Ka Rauza",
             "Persian-style funerary monument renowned for its glazed tilework.",
             4.2,
             None],
            ["Sikandra",
             "Suburb housing Akbar’s tomb and several Mughal-era monuments.",
             4.1,
             None],
            ["Mankameshwar Temple",
             "Ancient Shiva temple believed to be connected by a tunnel to the Agra Fort.",
             4.0,
             None],
            ["Wildlife SOS",
             "Rescue and rehabilitation center for sloth bears and elephants.",
             4.5,
             None],
            ["Keetham Lake (Sur Sarovar)",
             "Scenic lake and bird sanctuary offering boating and wildlife sightings.",
             4.2,
             None],
        ]
    ],
    [
        "Jaipur",
        "Known as the Pink City for its rosy-hued palaces, Jaipur is the vibrant capital of Rajasthan. "
        "Its grand forts, exquisite havelis, and bustling bazaars showcase Rajputana grandeur. "
        "A hub of art, culture, and royal heritage, Jaipur enchants travelers with its majestic charm.",
        [
            ["Amber Fort",
             "Colossal hilltop fortress with mirrored Sheesh Mahal and sweeping courtyard views.",
             4.7,
             "amber_fort.jpg"],
            ["Hawa Mahal",
             "Intricately latticed facade palace built for royal women to observe street festivals.",
             4.5,
             "hawa_mahal.jpg"],
            ["City Palace",
             "Lavish palace complex with museums, courtyards, and traditional Rajasthani architecture.",
             4.6,
             "city_palace.jpg"],
            ["Jantar Mantar",
             "Astronomical observatory featuring giant sundials and stone instruments.",
             4.4,
             "jantar_mantar.jpg"],
            ["Jal Mahal",
             "Picturesque palace situated mid-lake, best viewed from the lakeside promenade.",
             4.3,
             None],
            ["Albert Hall Museum",
             "Rajasthan’s oldest museum displaying art, carpets, and artifacts.",
             4.2,
             "albert_hall.jpg"],
            ["Nahargarh Fort",
             "Perched on Aravalli Hills, offering panoramic views of Jaipur city below.",
             4.5,
             "nahargarh_fort.jpg"],
            ["Jaigarh Fort",
             "Home to the world’s largest cannon on wheels, Jaivana.",
             4.4,
             None],
            ["Birla Mandir",
             "Modern marble temple dedicated to Lord Vishnu and Goddess Lakshmi.",
             4.6,
             None],
            ["Galtaji Temple",
             "Ancient pilgrimage site with natural springs and monkey inhabitants.",
             4.3,
             "galtaji.jpg"],
            ["Rambagh Palace",
             "Former royal residence now a luxury hotel set in manicured gardens.",
             4.7,
             None],
            ["Govind Dev Ji Temple",
             "Historic Krishna temple revered by devotees for its ornate carvings.",
             4.4,
             None],
        ]
    ],
    [
        "Varanasi",
        "Considered one of the world’s oldest living cities, Varanasi rests on the banks of the Ganges. "
        "It is a spiritual epicenter, famed for its ghats, temples, and vibrant rituals. "
        "The city’s timeless heritage and riverside ceremonies captivate pilgrims and tourists alike.",
        [
            ["Kashi Vishwanath Temple",
             "Ancient and revered Shiva temple drawing thousands of pilgrims daily.",
             4.8,
             None],
            ["Dashashwamedh Ghat",
             "Most famous ghat where evening Ganga Aarti ceremonies light up the riverside.",
             4.6,
             None],
            ["Assi Ghat",
             "Peaceful ghat popular for yogurt sessions and sunrise views.",
             4.4,
             None],
            ["Manikarnika Ghat",
             "Oldest cremation ghat, central to Hindu funeral rites.",
             4.1,
             None],
            ["Sarnath",
             "Nearby Buddhist site where Lord Buddha gave his first sermon.",
             4.7,
             "sarnath.jpg"],
            ["Ramnagar Fort",
             "18th-century fort and palace across the Ganges with museum exhibits.",
             4.3,
             None],
            ["Alamgir Mosque",
             "Also known as Beni Madhav Ka Darera, featuring Mughal architecture.",
             4.0,
             None],
            ["Banaras Hindu University",
             "Renowned university campus with Bharat Kala Bhavan museum.",
             4.5,
             None],
            ["Tulsi Manas Temple",
             "Marble temple inscribed with verses from the Ramcharitmanas.",
             4.4,
             None],
            ["Bharat Kala Bhavan",
             "Art museum housing collections of paintings, textiles, and sculptures.",
             4.2,
             None],
            ["Ganga Aarti Ceremony",
             "Daily ritual with priests offering lamps and chants at the riverbank.",
             4.9,
             None],
            ["Bharat Mata Mandir",
             "Unique temple featuring a relief map of India carved in marble.",
             4.3,
             None],
        ]
    ],
    [
        "Udaipur",
        "Often called the Venice of the East, Udaipur is famed for its lakes and palaces. "
        "Set against the backdrop of the Aravalli Hills, the city is a jewel of Mewar architecture. "
        "Romantic boat rides, vibrant bazaars, and regal heritage define Udaipur’s charm.",
        [
            ["City Palace",
             "Grand palace complex with museums, courtyards, and stunning lake views.",
             4.7,
             "udaipur_city_palace.jpg"],
            ["Lake Pichola",
             "Scenic artificial lake ideal for sunset boat rides.",
             4.6,
             None],
            ["Jag Mandir",
             "Island palace set amidst Lake Pichola, known for Mughal design.",
             4.5,
             "jag_mandir.jpg"],
            ["Jagdish Temple",
             "17th-century temple dedicated to Lord Vishnu with intricate carvings.",
             4.4,
             None],
            ["Saheliyon ki Bari",
             "Garden of maidens featuring fountains, kiosks, and lotus pools.",
             4.3,
             None],
            ["Fateh Sagar Lake",
             "Popular lake with islands and boat facilities.",
             4.2,
             None],
            ["Sajjangarh Palace",
             "Also called the Monsoon Palace, offering panoramic hilltop views.",
             4.4,
             "sajjangarh_palace.jpg"],
            ["Bagore Ki Haveli",
             "18th-century haveli turned museum showcasing Rajasthani artifacts.",
             4.3,
             None],
            ["Bhartiya Lok Kala Museum",
             "Museum dedicated to folk art, puppetry, and tribal crafts.",
             4.1,
             None],
            ["Shilpgram",
             "Rural arts and crafts complex hosting cultural festivals.",
             4.0,
             None],
            ["Bada Mahal",
             "18th-century pleasure palace set amid gardens and fountains.",
             4.0,
             None],
            ["Ahar Cenotaphs",
             "Ancient royal cremation ground with marble cenotaphs.",
             4.2,
             None],
        ]
    ],
    [
        "Shimla",
        "Perched on the ridge of the Lower Himalayas, Shimla was the summer capital of British India. "
        "The town is celebrated for its colonial architecture, scenic vistas, and pleasant summer climate. "
        "A hub for mountain enthusiasts, Shimla offers a blend of heritage and natural beauty.",
        [
            ["The Ridge",
             "Open street along Mall Road offering panoramic views of the Himalayas.",
             4.6,
             None],
            ["Mall Road",
             "Lively pedestrian street lined with shops, eateries, and colonial buildings.",
             4.5,
             None],
            ["Jakhoo Temple",
             "Hilltop temple dedicated to Lord Hanuman with a giant statue.",
             4.4,
             None],
            ["Christ Church",
             "Neo-Gothic church and one of the oldest in North India.",
             4.3,
             None],
            ["Kufri",
             "Hill station near Shimla known for skiing and Himalayan wildlife.",
             4.4,
             None],
            ["Glen",
             "Lush valley and picnic spot with dense forests and a stream.",
             4.1,
             None],
            ["Chadwick Falls",
             "Picturesque waterfall surrounded by Deodar trees.",
             4.2,
             None],
            ["Summer Hill",
             "Quiet suburb with walking trails and views over Shimla.",
             4.0,
             None],
            ["Viceregal Lodge",
             "Grand colonial building once the summer residence of the Viceroy of India.",
             4.5,
             None],
            ["Scandal Point",
             "Historic junction with scenic views and the story of a famous royal romance.",
             4.1,
             None],
            ["Tara Devi Temple",
             "Hilltop temple dedicated to Goddess Tara with Himalayan vistas.",
             4.0,
             None],
            ["Annandale",
             "Grounds used for polo matches and cricket, set amid oak and deodar trees.",
             4.2,
             None],
        ]
    ],
    [
        "Darjeeling",
        "Famous for its tea gardens and panoramic views of Mount Kanchenjunga, Darjeeling sits at 2,050 meters. "
        "The town’s colonial-era charm, toy train rides, and Buddhist monasteries attract nature and culture enthusiasts. "
        "Darjeeling’s unique blend of history and natural beauty makes it a must-visit Himalayan retreat.",
        [
            ["Tiger Hill",
             "Renowned viewpoint for sunrise views over Mount Kanchenjunga and the Himalayas.",
             4.8,
             None],
            ["Batasia Loop",
             "Spiral railway loop offering landscaped gardens and a war memorial.",
             4.6,
             None],
            ["Darjeeling Himalayan Railway",
             "Historic narrow-gauge ‘Toy Train’ ride showcasing scenic mountain routes.",
             4.7,
             "toy_train.jpg"],
            ["Padmaja Naidu Himalayan Zoological Park",
             "High-altitude zoo housing endangered Himalayan species like snow leopards.",
             4.5,
             "hill_zoo.jpg"],
            ["Himalayan Mountaineering Institute",
             "Training center and museum dedicated to mountaineering history and gear.",
             4.4,
             None],
            ["Peace Pagoda",
             "Buddhist stupa offering panoramic mountain vistas and tranquil ambiance.",
             4.6,
             None],
            ["Ghoom Monastery",
             "One of the oldest Tibetan Buddhist monasteries, home to a 15-foot Maitreya Buddha.",
             4.5,
             None],
            ["Happy Valley Tea Estate",
             "Historic tea garden providing guided tours and tastings.",
             4.4,
             None],
            ["Chowrasta",
             "Popular mall road square lined with shops, eateries, and street performances.",
             4.3,
             None],
            ["Observatory Hill",
             "Hilltop site with Buddhist monastery ruins and scenic viewpoints.",
             4.2,
             None],
            ["Rock Garden",
             "Terraced waterfalls and manicured gardens set amid a lush forest.",
             4.1,
             None],
            ["Seven Sisters Falls",
             "Series of cascading waterfalls named after the Pahari legend of seven sisters.",
             4.0,
             None],
        ]
    ],
    [
        "Goa",
        "Renowned for its sun-kissed beaches and vibrant nightlife, Goa blends Portuguese heritage with Indian culture. "
        "Coastal villages showcase colonial architecture, bustling markets, and spice plantations. "
        "From serene retreats to lively shacks, Goa offers diverse experiences for every traveler.",
        [
            ["Baga Beach",
            "Popular beach known for water sports, lively shacks, and spectacular sunset parties.",
            4.5,
            "baga_beach.jpg"],
            ["Calangute Beach",
            "The largest beach in North Goa, lined with shops, cafés, and vibrant activity stalls.",
            4.4,
            None],
            ["Fort Aguada",
            "17th-century Portuguese fort offering panoramic Arabian Sea views and a historic lighthouse.",
            4.6,
            "aguada_fort.jpg"],
            ["Basilica of Bom Jesus",
            "UNESCO World Heritage church housing the relics of St. Francis Xavier.",
            4.7,
            None],
            ["Anjuna Flea Market",
            "Weekly open-air market selling handicrafts, jewelry, and local delicacies.",
            4.3,
            None],
            ["Dudhsagar Falls",
            "Spectacular four-tiered waterfall set within Bhagwan Mahaveer Sanctuary, perfect for trekking.",
            4.8,
            None],
            ["Chapora Fort",
            "Historic fort overlooking Vagator Beach, famous from its feature in 'Dil Chahta Hai'.", 
            4.2,
            None],
            ["Palolem Beach",
            "Scenic south Goa beach with calm waters, ideal for kayaking and dolphin spotting.",
            4.4,
            None],
            ["Spice Plantations",
            "Guided tours through aromatic plantations showcasing local spices and traditional processing.",
            4.3,
            None],
            ["Church of Our Lady of the Immaculate Conception",
            "Iconic white church in Panaji with a distinctive bell tower and colonial-era architecture.",
            4.5,
            None],
            ["Snow Park Goa",
            "Indoor theme park offering snow activities like skiing, snowboarding, and snowball fights.",
            4.1,
            None],
            ["Fontainhas",
            "Historic Latin Quarter of Panaji with colorful Portuguese-style houses and quaint cafés.",
            4.4,
            None],
        ]
    ]
]